#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: Build_x86_64

on: 
  release:
    types: [published]

#  push:
#    branches: 
#      - master

  schedule:
    - cron: 0 12 1,16 * *
  
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf wget curl swig rsync ccache curl wget vim nano python python-pip python3-pip python-ply python3-ply haveged lrzsz scons intltool wget mkisofs
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Clean
      working-directory: ./openwrt
      run: |
        ./scripts/feeds clean

    - name: Add packages
      working-directory: ./openwrt/package
      run: |
        git clone https://github.com/chenshuo890/eqos.git
        
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        echo "src-git helloworld https://github.com/fw876/helloworld " >> feeds.conf.default
        echo "src-git lienol https://github.com/Lienol/openwrt-package " >> feeds.conf.default
        echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall;packages " >> feeds.conf.default
        echo "src-git passwall_luci https://github.com/xiaorouji/openwrt-passwall;luci " >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Configuration Customization - Build_x86_64
      env:
        CONFIG_FILE: 'x86_64.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
        
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j10
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "Building."
        make -j$(($(nproc) + 1))

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Lean-OpenWRT-x64
        path: openwrt/bin/targets/x86/64
